set nocompatible              " required
filetype off                  " required
set ignorecase
set smartcase

call plug#begin('~/.vim/plugged')
Plug 'ap/vim-css-color'
Plug 'scrooloose/nerdtree'
Plug 'Valloric/YouCompleteMe'
Plug 'vim-syntastic/syntastic'
Plug 'vim-airline/vim-airline'
Plug 'joshdick/onedark.vim'
Plug 'tpope/vim-surround'
call plug#end()

"colorscheme
if (has("termguicolors"))
 set termguicolors
endif
let g:onedark_hide_endofbuffer=1
let g:onedark_terminal_italics=1
syntax on
colorscheme onedark 
" custom setting
set mouse=a
set number relativenumber
set encoding=utf-8
set backspace=indent,eol,start
set cursorline
set guioptions=
syntax on
"split settings
set splitbelow
set splitright

" indent for global
set expandtab
set shiftwidth=4
set softtabstop=4
set autoindent

" indent for special file
autocmd FileType c,cpp setlocal expandtab shiftwidth=2 softtabstop=2 cindent 
autocmd FileType python setlocal expandtab shiftwidth=4 softtabstop=4 autoindent

" setup for airline
let g:airline_theme='onedark'
let g:airline_section_b = '%{strftime("%a %d. %H:%M")}'
let g:airline_powerline_fonts = 1

"NERDTree settings
let NERDTreeShowHidden=1

"Disable background erase so that vim works properly with color schemes
set t_ut= 
