#! /bin/sh

sxhkd &

killall picom
picom &

mpd &

bspc monitor eDP-1 -d DEV WWW DOC ETC MEDIA 

#assigning windows to specific workspaces
bspc rule -a firefox desktop=^2 follow=on 
bspc rule -a kitty desktop=^1
bspc rule -a Spotify desktop=^5
bspc rule -a Zathura state=tiled
bspc rule -a Zathura desktop=^3

bspc config border_width 5
bspc config window_gap 30
bspc config top_padding 60
bspc config left_padding 30
bspc config right_padding 30
bspc config border_radius 15

#get xrdb colors
highlight=$(xrdb -query | grep "*.highlight" | cut -f 2)
background=$(xrdb -query | grep "*.background-no-transparancy:" | cut -f 2)

bspc config focused_border_color "$highlight"
bspc config normal_border_color "$background"

bspc config focus_follows_pointer true
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle false

feh --bg-center Pictures/Wallpapers/BrownWallpaper.jpg 
exec $HOME/.config/polybar/launch.sh
