#! /bin/sh

sxhkd &

killall compton 
compton & 

killall mpd
mpd &

bspc monitor eDP-1 -d DEV WWW DOC ETC MEDIA 

#assigning windows to specific workspaces
bspc rule -a firefox desktop=^2 follow=on 
bspc rule -a code-oss desktop=^1
bspc rule -a Spotify desktop=^5
bspc rule -a Zathura state=tiled
bspc rule -a Zathura desktop=^3

bspc config border_width 5
bspc config window_gap 30
bspc config top_padding 30
bspc config left_padding 30
bspc config right_padding 30

bspc config focused_border_color "#827044"
bspc config normal_border_color "#212121"

bspc config focus_follows_pointer true
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle false

feh --bg-center Pictures/Wallpapers/AoTWall.png

exec $HOME/.config/polybar/launch.sh
